### ISSUE TITLE
bug in the new pyptv version

### ISSUE THREAD

**Issue by alexlib** [alexlib/pyptv#40]
Wheel (zoom in / out) fails completely on Mac OS X with a strange bug 

```
 Detection procedure 

Traceback (most recent call last):
  File "/Users/alex/miniconda3/envs/pyptv/lib/python3.7/site-packages/enable/qt4/base_window.py", line 232, in wheelEvent
    self.handler.wheelEvent(event)
  File "/Users/alex/miniconda3/envs/pyptv/lib/python3.7/site-packages/enable/qt4/base_window.py", line 122, in wheelEvent
    self._enable_window._handle_mouse_event("mouse_wheel", event)
  File "/Users/alex/miniconda3/envs/pyptv/lib/python3.7/site-packages/enable/abstract_window.py", line 301, in _handle_mouse_event
    mouse_event = self._create_mouse_event(event)
  File "/Users/alex/miniconda3/envs/pyptv/lib/python3.7/site-packages/enable/qt4/base_window.py", line 411, in _create_mouse_event
    delta = event.delta()
AttributeError: 'QWheelEvent' object has no attribute 'delta'
Abort trap: 6
```

The main problem seems to be that we moved to PyQt5 but the error is in `enable/qt4 `

I don't even know how to deal with it. 

@zmbq - can you please see if there is something I can do to isolate the environment to be sure I get the installation with enable without qt4? Thanks

**Comment by zmbq** [comment]
Can you please provide a simple list of steps to reproduce this? Which file should I load, which option to select before trying to mouse-zoom?

**Comment by alexlib** [comment]
1. `pyptv` installation
2. `git clone http://github.com/openptv/test_cavity` 
3. `ptvgui test_cavity
4. Start -> Init/Restart (new images appear) 
5. anywhere in the image window middle button or wheel was doing zoom in/out. Now it fails with 

```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/pyptv/lib/python3.7/site-packages/enable/qt4/base_window.py", line 232, in wheelEvent
    self.handler.wheelEvent(event)
  File "/home/user/miniconda3/envs/pyptv/lib/python3.7/site-packages/enable/qt4/base_window.py", line 122, in wheelEvent
    self._enable_window._handle_mouse_event("mouse_wheel", event)
  File "/home/user/miniconda3/envs/pyptv/lib/python3.7/site-packages/enable/abstract_window.py", line 301, in _handle_mouse_event
    mouse_event = self._create_mouse_event(event)
  File "/home/user/miniconda3/envs/pyptv/lib/python3.7/site-packages/enable/qt4/base_window.py", line 411, in _create_mouse_event
    delta = event.delta()
AttributeError: 'QWheelEvent' object has no attribute 'delta'

```

**Comment by alexlib** [comment]
What I notice now is for some strange reason it says `qt4` which I have no idea how I got there. I do remember that PyQt5 was installed and it created this error.
