### ISSUE TITLE
bug (from the forum, Lukas)

### ISSUE THREAD

**Issue by alexlib** [alexlib/pyptv#8]
https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/openptv/u9C_mVoI8rc

```
Frame 10001 had [531, 474, 39] correspondences.
Traceback (most recent call last):
  File "/home/lengelen/.local/share/canopy/edm/envs/User/lib/python2.7/site-packages/pyface/ui/qt4/action/action_item.py", line 160, in _qt4_on_triggered
    self.controller.perform(action)
  File "/home/lengelen/.local/share/canopy/edm/envs/User/lib/python2.7/site-packages/traitsui/qt4/ui_base.py", line 138, in perform
    self.ui.do_undoable( self._perform, action )
  File "/home/lengelen/.local/share/canopy/edm/envs/User/lib/python2.7/site-packages/traitsui/ui.py", line 715, in do_undoable
    action( *args, **kw )
  File "/home/lengelen/.local/share/canopy/edm/envs/User/lib/python2.7/site-packages/traitsui/qt4/ui_base.py", line 143, in _perform
    method( self.ui.info )
  File "pyptv_gui.py", line 627, in sequence_action
    ptv.py_sequence_loop(info.object)
  File "/disk/home/lengelen/openptv/pyptv/pyptv/ptv.py", line 217, in py_sequence_loop
    flat.transpose(1,0,2), cpar, cals, vpar)
  File "optv/orientation.pyx", line 70, in optv.orientation.point_positions (optv/orientation.c:2392)
TypeError: point_positions() takes exactly 3 positional arguments (4 given)
^CTraceback (most recent call last):
  File "/home/lengelen/.local/share/canopy/edm/envs/User/lib/python2.7/site-packages/traitsui/qt4/toolkit.py", line 377, in eventFilter
    def eventFilter(self, object, event):
```

**Comment by alexlib** [comment]
https://github.com/alexlib/pyptv/commit/ef2bc3b387ed7c7fd3e5dab848a5bde3bdd263ac fixes the bug #8
